name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - run: |
      dotnet restore
      bash run-coverage
    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        files: ./build/coverage/cov.xml
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true