name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Coverage test
      run: bash run-coverage.sh
      timeout-minutes: 2
    - name: Print coverage file contents
      run: cat ./build/coverage/cov.xml
    - name: Upload coverage to Codecov
      timeout-minutes: 2
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        files: ./build/coverage/cov.xml
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true
